# Generated by Django 2.1.7 on 2020-01-15 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(102), django.core.validators.MinValueValidator(0)])),
                ('HR', models.FloatField(default=0)),
                ('O2Sat', models.FloatField(default=0)),
                ('Temp', models.FloatField(default=0)),
                ('SBP', models.FloatField(default=0)),
                ('DBP', models.FloatField(default=0)),
                ('Resp', models.FloatField(default=0)),
                ('MAP', models.FloatField(default=0)),
            ],
        ),
    ]
